export interface Cluster {
  id: string;
  name: string;
  intent: string;
  heatLevel: number; // 1-5, how "hot" the potential client is
  keywords: string[];
}

export const CLUSTERS: Cluster[] = [
  {
    id: "admission-general",
    name: "Поступление (общее)",
    intent: "Готов поступать, ищет как",
    heatLevel: 5,
    keywords: [
      "Как поступить в США",
      "Поступление в сша",
      "Бакалавриат в США",
      "Gap year перед поступлением в США",
      "Community college США",
      "Перевод из российского вуза в американский",
      "Отличие бакалавриата США от Европы",
      "Как поступить в американский университет",
      "Поступить в Европу",
      "Поступить в Англию",
      "Поступить в Канаду",
      "Поступить в Германию",
      "Поступить в Корею",
      "Поступить в Китай",
      "Поступить в Японию",
      "Как подать документы в университет",
      "Foundation year программа",
      "Pathway program",
      "Dual enrollment США",
      "Transfer student",
    ],
  },
  {
    id: "masters-phd-mba",
    name: "Магистратура / PhD / MBA",
    intent: "Конкретная программа, горячий клиент",
    heatLevel: 5,
    keywords: [
      "Магистратура в сша",
      "MBA в сша",
      "Phd в сша",
      "Магистратура в Европе",
      "Магистратура в Англии",
      "MBA в Европе",
      "PhD в Европе",
      "Аспирантура за рубежом",
      "Докторантура за рубежом",
    ],
  },
  {
    id: "scholarships",
    name: "Стипендии и финансирование",
    intent: "Ищет деньги на учёбу",
    heatLevel: 4,
    keywords: [
      "Стипендии в сша",
      "Спортивная стипендия США",
      "Financial aid для иностранных студентов",
      "Need blind admission",
      "Полная стипендия за рубежом",
      "Бесплатное обучение за рубежом",
      "Fulbright стипендия",
      "Erasmus стипендия",
      "DAAD стипендия",
      "Chevening стипендия",
      "Merit scholarship",
      "Full ride scholarship",
      "Fee waiver",
      "Стипендиальная программа",
      "Scholarship essay",
    ],
  },
  {
    id: "exams",
    name: "Экзамены",
    intent: "Подготовка, средняя стадия воронки",
    heatLevel: 3,
    keywords: [
      "Экзамен SAT",
      "SAT подготовка",
      "SAT math",
      "SAT reading",
      "ACT экзамен",
      "Экзамен gre как сдать",
      "GRE подготовка",
      "Экзамен gmat",
      "GMAT подготовка",
      "AP экзамены для поступления",
      "AP calculus",
      "AP physics",
      "Подготовка к TOEFL",
      "TOEFL iBT",
      "IELTS или TOEFL для США",
      "IELTS speaking",
      "IELTS writing",
      "Duolingo English Test",
      "Учеба в США без SAT",
      "Practice test SAT",
    ],
  },
  {
    id: "documents",
    name: "Документы и заявка",
    intent: "Активно готовит документы",
    heatLevel: 4,
    keywords: [
      "эссе для учебы в сша",
      "мотивационное письмо для сша",
      "Рекомендательные письма сша",
      "портфолио для учебы в сша",
      "Common app как заполнять",
      "Интервью учеба в сша",
      "активности для поступления в сша",
      "CSS Profile как заполнить",
      "Как написать why essay",
      "Supplemental essays советы",
      "Успешное интервью в университет",
      "Extracurricular activities для поступления",
      "Волонтерство для поступления в США",
      "Personal statement как написать",
      "Statement of purpose",
      "Letter of recommendation",
      "UCAS как подать",
      "Coalition App",
      "FAFSA как заполнить",
      "Аттестат для поступления",
      "Нотариальный перевод документов",
      "Апостиль для университета",
    ],
  },
  {
    id: "universities",
    name: "Выбор вуза",
    intent: "Исследует варианты",
    heatLevel: 3,
    keywords: [
      "Университет сша",
      "Как выбрать вуз сша",
      "лучший универ сша",
      "Гарвард",
      "Гарвард поступить",
      "Стенфорд поступить",
      "Лига плюща",
      "Liberal arts college США",
      "Как попасть в Ivy League",
      "STEM специальности США",
      "MIT",
      "Yale",
      "Princeton",
      "Columbia University",
      "NYU",
      "UCLA",
      "Berkeley",
      "Duke University",
      "Georgetown",
      "Оксфорд",
      "Кембридж",
      "ETH Zurich",
      "University of Toronto",
      "McGill",
      "Рейтинг университетов",
      "QS ranking",
      "US News ranking",
    ],
  },
  {
    id: "fields-of-study",
    name: "Специальности",
    intent: "Выбирает направление обучения",
    heatLevel: 3,
    keywords: [
      "Computer science за рубежом",
      "Медицина в США",
      "Law school США",
      "Business school",
      "Engineering за рубежом",
      "Data science обучение",
      "Психология за рубежом",
      "Архитектура за рубежом",
      "Film school",
      "Art school",
      "STEM специальности",
    ],
  },
  {
    id: "visa",
    name: "Виза и после поступления",
    intent: "Уже поступил, нужна виза / OPT",
    heatLevel: 4,
    keywords: [
      "Как получить визу F-1",
      "OPT после учебы в США",
      "Студенческая виза",
      "J-1 виза",
      "CPT разрешение на работу",
      "H1B после учебы",
      "Post-study work visa",
      "Work permit после учебы",
    ],
  },
  {
    id: "student-life",
    name: "Жизнь студента",
    intent: "Интересуется бытом и расходами",
    heatLevel: 2,
    keywords: [
      "Кампус тур американского университета",
      "Общежитие в американском университете",
      "Стоимость обучения в США",
      "Подработка для студентов в США",
      "Жизнь студента в США",
      "Адаптация за рубежом",
      "Culture shock",
      "Бюджет студента за рубежом",
      "Сколько стоит учеба",
      "Аренда жилья для студентов",
      "Медицинская страховка студента",
      "Работа во время учебы",
      "Карьера после университета",
    ],
  },
  {
    id: "application-process",
    name: "Процесс подачи",
    intent: "Разбирается в процедуре подачи",
    heatLevel: 4,
    keywords: [
      "Application deadline вузы США",
      "Early decision early action",
      "Waitlist вуза США что делать",
      "Regular decision",
      "Rolling admission",
      "Acceptance rate",
      "Conditional offer",
      "Отказ из университета",
      "Appeal отказ",
      "Admitted students day",
    ],
  },
  {
    id: "general-education",
    name: "Образование за рубежом (общее)",
    intent: "Общий интерес к зарубежному образованию",
    heatLevel: 2,
    keywords: [
      "Образование за рубежом",
      "Учеба за границей",
      "Высшее образование за рубежом",
      "Диплом за рубежом",
      "Exchange program",
      "Обмен студентами",
      "Семестр за рубежом",
      "Летняя школа за рубежом",
      "Summer school",
      "Языковые курсы за рубежом",
      "Онлайн образование",
      "Нострификация диплома",
    ],
  },
];

export function getClusterForKeyword(text: string): Cluster | null {
  const lower = text.toLowerCase();
  for (const cluster of CLUSTERS) {
    if (cluster.keywords.some((k) => k.toLowerCase() === lower)) {
      return cluster;
    }
  }
  return null;
}
