// Keyword → heatLevel matching (fuzzy, lowercase)
// Order matters within each level — specific patterns checked before broad catch-alls
export const HEAT_MAP: { pattern: string; heat: number }[] = [
  // ═══════════════════════════════════════════════════════════════
  // HEAT 5 — HOT: Ready to apply, searching for HOW to get in
  // ═══════════════════════════════════════════════════════════════

  // Direct admission queries — USA
  { pattern: "поступить в сша", heat: 5 },
  { pattern: "поступление в сша", heat: 5 },
  { pattern: "поступить в америку", heat: 5 },
  { pattern: "поступление в америку", heat: 5 },
  { pattern: "как поступить в американский университет", heat: 5 },
  { pattern: "как поступить в американский вуз", heat: 5 },
  { pattern: "поступить в американский колледж", heat: 5 },

  // Direct admission queries — Europe
  { pattern: "поступить в европу", heat: 5 },
  { pattern: "поступление в европу", heat: 5 },
  { pattern: "поступить в англию", heat: 5 },
  { pattern: "поступление в англию", heat: 5 },
  { pattern: "поступить в великобританию", heat: 5 },
  { pattern: "поступить в германию", heat: 5 },
  { pattern: "поступление в германию", heat: 5 },
  { pattern: "поступить в голландию", heat: 5 },
  { pattern: "поступить в нидерланды", heat: 5 },
  { pattern: "поступить в чехию", heat: 5 },
  { pattern: "поступить в италию", heat: 5 },
  { pattern: "поступить в испанию", heat: 5 },
  { pattern: "поступить в францию", heat: 5 },
  { pattern: "поступить в швейцарию", heat: 5 },
  { pattern: "поступить в австрию", heat: 5 },
  { pattern: "поступить в финляндию", heat: 5 },
  { pattern: "поступить в швецию", heat: 5 },
  { pattern: "поступить в норвегию", heat: 5 },
  { pattern: "поступить в данию", heat: 5 },

  // Direct admission queries — Asia/Other
  { pattern: "поступить в канаду", heat: 5 },
  { pattern: "поступление в канаду", heat: 5 },
  { pattern: "поступить в австралию", heat: 5 },
  { pattern: "поступить в корею", heat: 5 },
  { pattern: "поступить в южную корею", heat: 5 },
  { pattern: "поступить в китай", heat: 5 },
  { pattern: "поступить в японию", heat: 5 },
  { pattern: "поступить в сингапур", heat: 5 },
  { pattern: "поступить в гонконг", heat: 5 },
  { pattern: "поступить в оаэ", heat: 5 },
  { pattern: "поступить в дубай", heat: 5 },

  // General admission queries
  { pattern: "поступление за границу", heat: 5 },
  { pattern: "поступить за рубеж", heat: 5 },
  { pattern: "как подать документы в университет", heat: 5 },
  { pattern: "подать заявку в университет", heat: 5 },
  { pattern: "подать заявку в вуз", heat: 5 },
  { pattern: "как подать заявку", heat: 5 },

  // Specific degree programs
  { pattern: "бакалавриат в сша", heat: 5 },
  { pattern: "бакалавриат за рубежом", heat: 5 },
  { pattern: "бакалавриат в европе", heat: 5 },
  { pattern: "бакалавриат в канаде", heat: 5 },
  { pattern: "бакалавриат в англии", heat: 5 },
  { pattern: "магистратура", heat: 5 },
  { pattern: "mba", heat: 5 },
  { pattern: "phd", heat: 5 },
  { pattern: "аспирантура", heat: 5 },
  { pattern: "докторантура", heat: 5 },
  { pattern: "associate degree", heat: 5 },

  // Transfer / bridge / prep
  { pattern: "gap year", heat: 5 },
  { pattern: "community college", heat: 5 },
  { pattern: "перевод из российского", heat: 5 },
  { pattern: "перевод в университет", heat: 5 },
  { pattern: "transfer student", heat: 5 },
  { pattern: "foundation year", heat: 5 },
  { pattern: "подготовительные курсы", heat: 5 },
  { pattern: "pathway program", heat: 5 },
  { pattern: "pre-university", heat: 5 },
  { pattern: "dual enrollment", heat: 5 },

  // Action-oriented English terms
  { pattern: "admission", heat: 5 },
  { pattern: "apply to university", heat: 5 },
  { pattern: "how to apply", heat: 5 },
  { pattern: "enrollment", heat: 5 },
  { pattern: "зачисление", heat: 5 },

  // ═══════════════════════════════════════════════════════════════
  // HEAT 4 — WARM: Actively preparing documents/applications
  // ═══════════════════════════════════════════════════════════════

  // Application documents
  { pattern: "эссе", heat: 4 },
  { pattern: "мотивационное письмо", heat: 4 },
  { pattern: "рекомендательн", heat: 4 },
  { pattern: "портфолио", heat: 4 },
  { pattern: "personal statement", heat: 4 },
  { pattern: "statement of purpose", heat: 4 },
  { pattern: "letter of recommendation", heat: 4 },
  { pattern: "резюме для поступления", heat: 4 },
  { pattern: "cv для университета", heat: 4 },
  { pattern: "transcript", heat: 4 },
  { pattern: "аттестат", heat: 4 },
  { pattern: "диплом для поступления", heat: 4 },
  { pattern: "нотариальный перевод", heat: 4 },
  { pattern: "апостиль", heat: 4 },
  { pattern: "why essay", heat: 4 },
  { pattern: "supplemental", heat: 4 },
  { pattern: "scholarship essay", heat: 4 },

  // Application platforms
  { pattern: "common app", heat: 4 },
  { pattern: "css profile", heat: 4 },
  { pattern: "ucas", heat: 4 },
  { pattern: "coalition app", heat: 4 },
  { pattern: "fafsa", heat: 4 },

  // Application process & strategy
  { pattern: "deadline", heat: 4 },
  { pattern: "early decision", heat: 4 },
  { pattern: "early action", heat: 4 },
  { pattern: "regular decision", heat: 4 },
  { pattern: "rolling admission", heat: 4 },
  { pattern: "waitlist", heat: 4 },
  { pattern: "acceptance rate", heat: 4 },
  { pattern: "процент зачисления", heat: 4 },
  { pattern: "letter of acceptance", heat: 4 },
  { pattern: "conditional offer", heat: 4 },
  { pattern: "unconditional offer", heat: 4 },
  { pattern: "отказ из университета", heat: 4 },
  { pattern: "rejection", heat: 4 },
  { pattern: "appeal", heat: 4 },
  { pattern: "admitted students", heat: 4 },
  { pattern: "deferral", heat: 4 },
  { pattern: "отложенное зачисление", heat: 4 },

  // Scholarships & financial aid
  { pattern: "стипенди", heat: 4 },
  { pattern: "financial aid", heat: 4 },
  { pattern: "need blind", heat: 4 },
  { pattern: "need-blind", heat: 4 },
  { pattern: "need-based", heat: 4 },
  { pattern: "merit scholarship", heat: 4 },
  { pattern: "merit-based", heat: 4 },
  { pattern: "грант", heat: 4 },
  { pattern: "full ride", heat: 4 },
  { pattern: "полная стипендия", heat: 4 },
  { pattern: "бесплатное обучение", heat: 4 },
  { pattern: "fee waiver", heat: 4 },
  { pattern: "tuition waiver", heat: 4 },
  { pattern: "стипендиальная программа", heat: 4 },
  { pattern: "фулбрайт", heat: 4 },
  { pattern: "fulbright", heat: 4 },
  { pattern: "erasmus", heat: 4 },
  { pattern: "daad", heat: 4 },
  { pattern: "chevening", heat: 4 },
  { pattern: "scholarship", heat: 4 },

  // Interview
  { pattern: "интервью", heat: 4 },
  { pattern: "admission interview", heat: 4 },
  { pattern: "собеседование в университет", heat: 4 },

  // Visa & immigration
  { pattern: "виза", heat: 4 },
  { pattern: "f-1", heat: 4 },
  { pattern: "j-1", heat: 4 },
  { pattern: "студенческая виза", heat: 4 },
  { pattern: "student visa", heat: 4 },
  { pattern: "opt ", heat: 4 },
  { pattern: "cpt", heat: 4 },
  { pattern: "h1b после учебы", heat: 4 },
  { pattern: "work permit", heat: 4 },
  { pattern: "post-study work", heat: 4 },
  { pattern: "разрешение на работу", heat: 4 },

  // Extracurriculars & activities
  { pattern: "extracurricular", heat: 4 },
  { pattern: "активности для поступления", heat: 4 },
  { pattern: "волонтерство", heat: 4 },
  { pattern: "community service", heat: 4 },
  { pattern: "research opportunity", heat: 4 },
  { pattern: "научная работа", heat: 4 },
  { pattern: "олимпиада", heat: 4 },
  { pattern: "международная олимпиада", heat: 4 },
  { pattern: "hackathon", heat: 4 },
  { pattern: "хакатон", heat: 4 },
  { pattern: "стажировка", heat: 4 },
  { pattern: "internship", heat: 4 },
  { pattern: "leadership", heat: 4 },
  { pattern: "лидерство", heat: 4 },
  { pattern: "внеклассная деятельность", heat: 4 },

  // ═══════════════════════════════════════════════════════════════
  // HEAT 3 — MEDIUM: Researching options, exams, universities
  // ═══════════════════════════════════════════════════════════════

  // Standardized exams
  { pattern: "sat подготовка", heat: 3 },
  { pattern: "sat math", heat: 3 },
  { pattern: "sat reading", heat: 3 },
  { pattern: "sat writing", heat: 3 },
  { pattern: "sat tips", heat: 3 },
  { pattern: "sat score", heat: 3 },
  { pattern: "sat", heat: 3 },
  { pattern: "act подготовка", heat: 3 },
  { pattern: "act exam", heat: 3 },
  { pattern: "act", heat: 3 },
  { pattern: "gre подготовка", heat: 3 },
  { pattern: "gre", heat: 3 },
  { pattern: "gmat подготовка", heat: 3 },
  { pattern: "gmat", heat: 3 },
  { pattern: "toefl ibt", heat: 3 },
  { pattern: "toefl подготовка", heat: 3 },
  { pattern: "toefl", heat: 3 },
  { pattern: "ielts speaking", heat: 3 },
  { pattern: "ielts writing", heat: 3 },
  { pattern: "ielts reading", heat: 3 },
  { pattern: "ielts listening", heat: 3 },
  { pattern: "ielts подготовка", heat: 3 },
  { pattern: "ielts", heat: 3 },
  { pattern: "duolingo english test", heat: 3 },
  { pattern: "duolingo english", heat: 3 },
  { pattern: "cambridge exam", heat: 3 },
  { pattern: "ap calculus", heat: 3 },
  { pattern: "ap physics", heat: 3 },
  { pattern: "ap chemistry", heat: 3 },
  { pattern: "ap biology", heat: 3 },
  { pattern: "ap history", heat: 3 },
  { pattern: "ap computer science", heat: 3 },
  { pattern: "ap экзамен", heat: 3 },
  { pattern: "экзамен", heat: 3 },
  { pattern: "подготовка к экзамену", heat: 3 },
  { pattern: "test prep", heat: 3 },
  { pattern: "practice test", heat: 3 },
  { pattern: "mock exam", heat: 3 },

  // Top US universities — Ivy League
  { pattern: "гарвард", heat: 3 },
  { pattern: "harvard", heat: 3 },
  { pattern: "стенфорд", heat: 3 },
  { pattern: "stanford", heat: 3 },
  { pattern: "mit", heat: 3 },
  { pattern: "yale", heat: 3 },
  { pattern: "йель", heat: 3 },
  { pattern: "princeton", heat: 3 },
  { pattern: "принстон", heat: 3 },
  { pattern: "columbia university", heat: 3 },
  { pattern: "колумбийский университет", heat: 3 },
  { pattern: "upenn", heat: 3 },
  { pattern: "пенсильванский университет", heat: 3 },
  { pattern: "cornell", heat: 3 },
  { pattern: "корнелл", heat: 3 },
  { pattern: "brown university", heat: 3 },
  { pattern: "браун", heat: 3 },
  { pattern: "dartmouth", heat: 3 },
  { pattern: "дартмут", heat: 3 },
  { pattern: "ivy league", heat: 3 },
  { pattern: "лига плюща", heat: 3 },

  // Top US universities — other
  { pattern: "caltech", heat: 3 },
  { pattern: "калтех", heat: 3 },
  { pattern: "berkeley", heat: 3 },
  { pattern: "беркли", heat: 3 },
  { pattern: "ucla", heat: 3 },
  { pattern: "nyu", heat: 3 },
  { pattern: "duke", heat: 3 },
  { pattern: "дьюк", heat: 3 },
  { pattern: "georgetown", heat: 3 },
  { pattern: "джорджтаун", heat: 3 },
  { pattern: "johns hopkins", heat: 3 },
  { pattern: "джонс хопкинс", heat: 3 },
  { pattern: "carnegie mellon", heat: 3 },
  { pattern: "карнеги меллон", heat: 3 },
  { pattern: "georgia tech", heat: 3 },
  { pattern: "michigan university", heat: 3 },
  { pattern: "university of michigan", heat: 3 },
  { pattern: "rice university", heat: 3 },
  { pattern: "vanderbilt", heat: 3 },
  { pattern: "emory", heat: 3 },
  { pattern: "usc", heat: 3 },
  { pattern: "boston university", heat: 3 },
  { pattern: "northeastern", heat: 3 },
  { pattern: "purdue", heat: 3 },
  { pattern: "penn state", heat: 3 },
  { pattern: "university of texas", heat: 3 },
  { pattern: "university of illinois", heat: 3 },
  { pattern: "university of washington", heat: 3 },
  { pattern: "uc san diego", heat: 3 },
  { pattern: "uc davis", heat: 3 },
  { pattern: "uc santa barbara", heat: 3 },
  { pattern: "university of florida", heat: 3 },
  { pattern: "notre dame", heat: 3 },
  { pattern: "williams college", heat: 3 },
  { pattern: "amherst college", heat: 3 },
  { pattern: "pomona college", heat: 3 },
  { pattern: "swarthmore", heat: 3 },
  { pattern: "wellesley", heat: 3 },
  { pattern: "babson", heat: 3 },

  // UK/Europe universities
  { pattern: "оксфорд", heat: 3 },
  { pattern: "oxford", heat: 3 },
  { pattern: "cambridge university", heat: 3 },
  { pattern: "кембридж", heat: 3 },
  { pattern: "eth zurich", heat: 3 },
  { pattern: "imperial college", heat: 3 },
  { pattern: "lse", heat: 3 },
  { pattern: "ucl", heat: 3 },
  { pattern: "king's college", heat: 3 },
  { pattern: "edinburgh university", heat: 3 },
  { pattern: "сорбонна", heat: 3 },
  { pattern: "sorbonne", heat: 3 },
  { pattern: "tu munich", heat: 3 },
  { pattern: "tu berlin", heat: 3 },

  // Canada/Asia universities
  { pattern: "toronto university", heat: 3 },
  { pattern: "university of toronto", heat: 3 },
  { pattern: "mcgill", heat: 3 },
  { pattern: "waterloo", heat: 3 },
  { pattern: "ubc", heat: 3 },
  { pattern: "сеульский университет", heat: 3 },
  { pattern: "токийский университет", heat: 3 },
  { pattern: "nus singapore", heat: 3 },
  { pattern: "kaist", heat: 3 },
  { pattern: "university of tokyo", heat: 3 },
  { pattern: "seoul national", heat: 3 },
  { pattern: "tsinghua", heat: 3 },
  { pattern: "peking university", heat: 3 },

  // University types & rankings
  { pattern: "рейтинг университетов", heat: 3 },
  { pattern: "top universities", heat: 3 },
  { pattern: "лучшие университеты", heat: 3 },
  { pattern: "qs ranking", heat: 3 },
  { pattern: "us news ranking", heat: 3 },
  { pattern: "college ranking", heat: 3 },
  { pattern: "research university", heat: 3 },
  { pattern: "state university", heat: 3 },
  { pattern: "public university", heat: 3 },
  { pattern: "private university", heat: 3 },
  { pattern: "hbcu", heat: 3 },
  { pattern: "liberal arts", heat: 3 },
  { pattern: "stem", heat: 3 },

  // General university terms
  { pattern: "университет", heat: 3 },
  { pattern: "универ", heat: 3 },
  { pattern: "вуз", heat: 3 },

  // Fields of study
  { pattern: "computer science", heat: 3 },
  { pattern: "информатика", heat: 3 },
  { pattern: "программирование", heat: 3 },
  { pattern: "медицина в сша", heat: 3 },
  { pattern: "медицинский факультет", heat: 3 },
  { pattern: "pre-med", heat: 3 },
  { pattern: "юриспруденция", heat: 3 },
  { pattern: "law school", heat: 3 },
  { pattern: "бизнес школа", heat: 3 },
  { pattern: "business school", heat: 3 },
  { pattern: "engineering", heat: 3 },
  { pattern: "инженерия", heat: 3 },
  { pattern: "инженерн", heat: 3 },
  { pattern: "data science", heat: 3 },
  { pattern: "artificial intelligence", heat: 3 },
  { pattern: "биология", heat: 3 },
  { pattern: "химия", heat: 3 },
  { pattern: "физика", heat: 3 },
  { pattern: "математика", heat: 3 },
  { pattern: "экономика", heat: 3 },
  { pattern: "финансы", heat: 3 },
  { pattern: "psychology", heat: 3 },
  { pattern: "психология", heat: 3 },
  { pattern: "архитектура", heat: 3 },
  { pattern: "дизайн", heat: 3 },
  { pattern: "film school", heat: 3 },
  { pattern: "музыкальный колледж", heat: 3 },
  { pattern: "art school", heat: 3 },
  { pattern: "специальность", heat: 3 },
  { pattern: "major", heat: 3 },
  { pattern: "minor", heat: 3 },
  { pattern: "факультет", heat: 3 },

  // Comparisons
  { pattern: "сша или европа", heat: 3 },
  { pattern: "сша или канада", heat: 3 },
  { pattern: "сша или англия", heat: 3 },
  { pattern: "бакалавриат или магистратура", heat: 3 },
  { pattern: "community college или университет", heat: 3 },
  { pattern: "сша или великобритания", heat: 3 },

  // ═══════════════════════════════════════════════════════════════
  // HEAT 2 — COOL: General interest, student life, costs
  // ═══════════════════════════════════════════════════════════════

  // Student life
  { pattern: "кампус", heat: 2 },
  { pattern: "общежити", heat: 2 },
  { pattern: "dormitory", heat: 2 },
  { pattern: "student housing", heat: 2 },
  { pattern: "campus life", heat: 2 },
  { pattern: "жизнь студента", heat: 2 },
  { pattern: "student life", heat: 2 },
  { pattern: "адаптация", heat: 2 },
  { pattern: "culture shock", heat: 2 },
  { pattern: "культурный шок", heat: 2 },
  { pattern: "homesick", heat: 2 },
  { pattern: "тоска по дому", heat: 2 },
  { pattern: "друзья за границей", heat: 2 },
  { pattern: "социальная жизнь", heat: 2 },
  { pattern: "fraternity", heat: 2 },
  { pattern: "sorority", heat: 2 },
  { pattern: "студенческая организация", heat: 2 },
  { pattern: "клуб в университете", heat: 2 },

  // Costs & budgeting
  { pattern: "стоимость обучения", heat: 2 },
  { pattern: "tuition", heat: 2 },
  { pattern: "cost of living", heat: 2 },
  { pattern: "бюджет студента", heat: 2 },
  { pattern: "сколько стоит учеба", heat: 2 },
  { pattern: "сколько стоит жить", heat: 2 },
  { pattern: "аренда жилья", heat: 2 },
  { pattern: "health insurance", heat: 2 },
  { pattern: "медицинская страховка", heat: 2 },
  { pattern: "meal plan", heat: 2 },
  { pattern: "student loan", heat: 2 },
  { pattern: "студенческий кредит", heat: 2 },

  // Work
  { pattern: "подработка", heat: 2 },
  { pattern: "работа во время учебы", heat: 2 },
  { pattern: "работа после учебы", heat: 2 },
  { pattern: "карьера после университета", heat: 2 },
  { pattern: "зарплата после университета", heat: 2 },
  { pattern: "job market", heat: 2 },
  { pattern: "трудоустройство", heat: 2 },
  { pattern: "part-time job", heat: 2 },
  { pattern: "on-campus job", heat: 2 },

  // Living abroad
  { pattern: "жизнь в сша", heat: 2 },
  { pattern: "жизнь в канаде", heat: 2 },
  { pattern: "жизнь в англии", heat: 2 },
  { pattern: "жизнь в европе", heat: 2 },
  { pattern: "жизнь за границей", heat: 2 },
  { pattern: "жизнь за рубежом", heat: 2 },
  { pattern: "переезд в сша", heat: 2 },
  { pattern: "переезд за границу", heat: 2 },
  { pattern: "эмиграция", heat: 2 },
  { pattern: "иммиграция", heat: 2 },

  // General education
  { pattern: "учеба в сша", heat: 2 },
  { pattern: "образование в сша", heat: 2 },
  { pattern: "образование за рубежом", heat: 2 },
  { pattern: "учеба за границей", heat: 2 },
  { pattern: "зарубежное образование", heat: 2 },
  { pattern: "высшее образование", heat: 2 },
  { pattern: "диплом за рубежом", heat: 2 },
  { pattern: "зарубежный диплом", heat: 2 },
  { pattern: "нострификация", heat: 2 },
  { pattern: "признание диплома", heat: 2 },
  { pattern: "онлайн образование", heat: 2 },
  { pattern: "дистанционное обучение", heat: 2 },
  { pattern: "exchange program", heat: 2 },
  { pattern: "обмен студентами", heat: 2 },
  { pattern: "семестр за рубежом", heat: 2 },
  { pattern: "semester abroad", heat: 2 },
  { pattern: "летняя школа", heat: 2 },
  { pattern: "summer school", heat: 2 },
  { pattern: "summer program", heat: 2 },
  { pattern: "языковые курсы", heat: 2 },
  { pattern: "учить английский", heat: 2 },
  { pattern: "школа за рубежом", heat: 2 },
  { pattern: "school abroad", heat: 2 },

  // Brand
  { pattern: "global generation", heat: 2 },
  { pattern: "глобал дженерейшн", heat: 2 },
  { pattern: "глобал генерейшн", heat: 2 },

  // ═══════════════════════════════════════════════════════════════
  // HEAT 1 — COLD: Tangential content, city life, vlogs
  // ═══════════════════════════════════════════════════════════════

  // US cities
  { pattern: "нью йорк", heat: 1 },
  { pattern: "нью-йорк", heat: 1 },
  { pattern: "new york", heat: 1 },
  { pattern: "бостон", heat: 1 },
  { pattern: "boston", heat: 1 },
  { pattern: "лос-анджелес", heat: 1 },
  { pattern: "лос анджелес", heat: 1 },
  { pattern: "los angeles", heat: 1 },
  { pattern: "сан-франциско", heat: 1 },
  { pattern: "сан франциско", heat: 1 },
  { pattern: "san francisco", heat: 1 },
  { pattern: "чикаго", heat: 1 },
  { pattern: "chicago", heat: 1 },
  { pattern: "вашингтон", heat: 1 },
  { pattern: "washington", heat: 1 },
  { pattern: "майами", heat: 1 },
  { pattern: "miami", heat: 1 },
  { pattern: "сиэтл", heat: 1 },
  { pattern: "seattle", heat: 1 },
  { pattern: "калифорния", heat: 1 },
  { pattern: "california", heat: 1 },
  { pattern: "техас", heat: 1 },
  { pattern: "флорида", heat: 1 },

  // European/Asian cities
  { pattern: "лондон", heat: 1 },
  { pattern: "london", heat: 1 },
  { pattern: "торонто", heat: 1 },
  { pattern: "toronto", heat: 1 },
  { pattern: "ванкувер", heat: 1 },
  { pattern: "vancouver", heat: 1 },
  { pattern: "сидней", heat: 1 },
  { pattern: "мельбурн", heat: 1 },
  { pattern: "берлин", heat: 1 },
  { pattern: "berlin", heat: 1 },
  { pattern: "мюнхен", heat: 1 },
  { pattern: "париж", heat: 1 },
  { pattern: "paris", heat: 1 },
  { pattern: "токио", heat: 1 },
  { pattern: "tokyo", heat: 1 },
  { pattern: "сеул", heat: 1 },
  { pattern: "seoul", heat: 1 },
  { pattern: "дубай", heat: 1 },
  { pattern: "dubai", heat: 1 },
  { pattern: "прага", heat: 1 },

  // General / vlog / lifestyle
  { pattern: "лекци", heat: 1 },
  { pattern: "влог", heat: 1 },
  { pattern: "vlog", heat: 1 },
  { pattern: "day in my life", heat: 1 },
  { pattern: "мой день", heat: 1 },
  { pattern: "мой опыт", heat: 1 },
  { pattern: "room tour", heat: 1 },
  { pattern: "рум тур", heat: 1 },
  { pattern: "what i eat", heat: 1 },
  { pattern: "study with me", heat: 1 },
  { pattern: "день студента", heat: 1 },
  { pattern: "мотивация", heat: 1 },
  { pattern: "motivation", heat: 1 },
  { pattern: "study vlog", heat: 1 },
  { pattern: "routine", heat: 1 },
  { pattern: "распорядок дня", heat: 1 },

  // ═══════════════════════════════════════════════════════════════
  // BROAD CATCH-ALLS (order matters — checked LAST)
  // ═══════════════════════════════════════════════════════════════
  { pattern: "поступить", heat: 5 },
  { pattern: "поступлени", heat: 5 },
  { pattern: "за границ", heat: 5 },
  { pattern: "бакалавр", heat: 5 },
  { pattern: "application", heat: 4 },
  { pattern: "абитуриент", heat: 4 },
  { pattern: "учеб", heat: 2 },
  { pattern: "америк", heat: 2 },
  { pattern: "образован", heat: 2 },
  { pattern: "обучени", heat: 2 },
  { pattern: "студент", heat: 2 },
  { pattern: "колледж", heat: 2 },
  { pattern: "college", heat: 2 },
  { pattern: "university", heat: 2 },
  { pattern: "учиться", heat: 2 },
];

export const HEAT_LABELS: Record<number, { label: string; color: string; bg: string; chartColor: string }> = {
  5: { label: "Hot", color: "text-red-400", bg: "bg-red-500/15 border-red-500/30", chartColor: "#ef4444" },
  4: { label: "Warm", color: "text-orange-400", bg: "bg-orange-500/15 border-orange-500/30", chartColor: "#f97316" },
  3: { label: "Medium", color: "text-yellow-400", bg: "bg-yellow-500/15 border-yellow-500/30", chartColor: "#eab308" },
  2: { label: "Cool", color: "text-blue-400", bg: "bg-blue-500/15 border-blue-500/30", chartColor: "#3b82f6" },
  1: { label: "Cold", color: "text-slate-400", bg: "bg-slate-500/15 border-slate-500/30", chartColor: "#64748b" },
  0: { label: "Untracked", color: "text-muted-foreground", bg: "bg-muted/50 border-border/40", chartColor: "#9ca3af" },
};

export function getHeatLevel(term: string): number {
  const lower = term.toLowerCase();
  let maxHeat = 0;
  for (const { pattern, heat } of HEAT_MAP) {
    if (lower.includes(pattern) && heat > maxHeat) {
      maxHeat = heat;
      if (maxHeat === 5) return 5; // can't go higher, short-circuit
    }
  }
  return maxHeat;
}
